package org.code.ruyin.util.snippet.ds.dao.entity;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_name
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.logo_url
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_datetime
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_datetime
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private Date updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_user
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_user
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.is_deleted
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_name
     *
     * @return the value of member.member_name
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_name
     *
     * @param memberName the value for member.member_name
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.logo_url
     *
     * @return the value of member.logo_url
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.logo_url
     *
     * @param logoUrl the value for member.logo_url
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_datetime
     *
     * @return the value of member.create_datetime
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_datetime
     *
     * @param createDatetime the value for member.create_datetime
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_datetime
     *
     * @return the value of member.update_datetime
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_datetime
     *
     * @param updateDatetime the value for member.update_datetime
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_user
     *
     * @return the value of member.create_user
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_user
     *
     * @param createUser the value for member.create_user
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_user
     *
     * @return the value of member.update_user
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_user
     *
     * @param updateUser the value for member.update_user
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.is_deleted
     *
     * @return the value of member.is_deleted
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.is_deleted
     *
     * @param isDeleted the value for member.is_deleted
     *
     * @mbg.generated Wed Apr 07 11:04:29 CST 2021
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}