spring:
  datasource:
    master:
      jdbc-url:
      username:
      password:
      driver-class-name:
    slave1:
      jdbc-url:
      username:
      password:
      driver-class-name:
    slave2:
      jdbc-url:
      username:
      password:
      driver-class-name: